### ISSUE TITLE
Live demo link throws 404

### ISSUE THREAD

**Issue by JRodDynamite** [kokes/nbviewer.js#16]
The live demo [link][link] on the README.md page shows a 404 page.

[link]:https://kokes.github.io/nbviewer.js/viewer.html

**Comment by kokes** [comment]
Works just fine for me, tried with three different internet providers. Maybe it was a github glitch then?

Edit: wait, it doesn't work on a different machine now. pages.github.com is partly down, so it seems to be a github issue.

**Comment by JRodDynamite** [comment]
Working fine for me now. I guess, you were right, GitHub Pages was partially down. Thanks for the library, btw! :smiley:
