### ISSUE TITLE
Problem when rendering ipynb

### ISSUE THREAD

**Issue by T-rain** [kokes/nbviewer.js#18]
I found some error when I rendered .ipynb like this.

<img width="1271" alt="error" src="https://cloud.githubusercontent.com/assets/6246859/25572760/15de4304-2e71-11e7-9897-49a737e98d16.png">

It should be

<img width="1195" alt="it_should_be" src="https://cloud.githubusercontent.com/assets/6246859/25572757/0f7e57c4-2e71-11e7-9f4d-0ff12efc493d.png">

In this commit [https://github.com/kokes/nbviewer.js/pull/17/commits/8098772cf979c9061828da55470b9c8ed872ef1b](https://github.com/kokes/nbviewer.js/pull/17/commits/8098772cf979c9061828da55470b9c8ed872ef1b)
I replace 
`dm.setAttribute('src', 'data:' + fmt + ';base64,' + dt.data[fmt].join(''));`
to
`dm.setAttribute('src', 'data:' + fmt + ';base64,' + dt.data[fmt]);`

It works fine.
When I print the `dt.data[fmt]`, it shows a base64 url.
I think the origin one is right.
If there is something that I've missed, please notify me

**Comment by kokes** [comment]
Thanks for the report. I was able to reproduce this and will push a fix shortly. I believe some images are indeed saved as lists of base64 strings, but the API has changed recently to be a single blob - I haven't checked the spec, but it's safer to be able to handle both.

[issue-18.ipynb.zip](https://github.com/kokes/nbviewer.js/files/967519/issue-18.ipynb.zip)
