### ISSUE TITLE
error:Join is not a function

### ISSUE THREAD

**Issue by songlin51** [kokes/nbviewer.js#44]
Hi kokes
i use nbviewer tips: Join is not a function 

code line : 304
```
function handle_mdown(cell) {
        console.log(cell)
        console.log(cell.source)
        var el = d.createElement('div');
        var source
        if(cell.source === Array){
            source = cell.source.join('');
        }else{
            source = cell.source
        }
        
        var latexed = source.replace(/\$\$([\s\S]+?)\$\$/g, latexer); // block-based math
        latexed = latexed.replace(/\$(.+?)\$/g, latexer); // inline math
        el.innerHTML = marked(latexed);

        return el;
    }
```

this is my ipynb file: [heijing.ipynb](https://github.com/songlin51/jandan/blob/master/heijng.ipynb)

I think the problem is because   source node 

i change handle_mdown func 
```
function handle_mdown(cell) {
        var el = d.createElement('div');
        var source
        if(cell.source === Array){
            source = cell.source.join('');
        }else{
            source = cell.source
        }

        var latexed = source.replace(/\$\$([\s\S]+?)\$\$/g, latexer); // block-based math
        latexed = latexed.replace(/\$(.+?)\$/g, latexer); // inline math
        el.innerHTML = marked(latexed);

        return el;
    }
```
My JS is very bad, I don't know if there will be potential errors in this modification

Finally, thank you for your efforts . Your project solved my problem

**Comment by kokes** [comment]
@songlin51 thanks for the report, I have fixed it in https://github.com/kokes/nbviewer.js/commit/ad90deda489393a64456754861c2f6d5f1e8e1b0, this should be live in our hosted viewer already.

Just out of curiosity - what versions of your tools (Python, Jupyter, operating system) did you use to produce this notebook? I'm used to seeing markdown entries as arrays, not strings, that's why it failed. Thanks!

**Comment by songlin51** [comment]
I use a Chinese education platform https://www.kesci.com/
The Notebook was created by the developers themselves
thanks
