### ISSUE TITLE
Choose a licence

### ISSUE THREAD

**Issue by kokes** [kokes/nbviewer.js#9]
Preferably
1. No restrictions on use or packaging (ie the licences of the work that uses this code) in private projects. I'd like to avoid any licensing conflicts.
2. Some basic attribution
3. It would be nice if people had to offer their forks to be merged here, to foster contribution and prevent diverging implementations, but I don't want it to be in conflict with point 1

**Comment by shakna-israel** [comment]
The [Apache](http://choosealicense.com/licenses/apache-2.0/) license sounds like it might fit what you want.

The requirement to state changes means that a lot of people tend to merge upstream, and not fragment.
